import React, { FC, ReactElement } from 'react';
import Head from 'next/head';

const Home: FC = (): ReactElement => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

export default Home;